#!/bin/bash

set -e

function install_virtual_box() {
	# https://ostechnix.com/check-linux-system-physical-virtual-machine/

	OS=$(uname -s)
	echo "$OS" | grep -qi "linux" || exit

	VIRTUALIZATION=$(hostnamectl | grep -i "virtualization" | cut -d ":" -f 2 | xargs)
	[ -z "$VIRTUALIZATION" ] && exit

	echo "$VIRTUALIZATION" | grep -qi "oracle" && {
		# https://wiki.debian.org/VirtualBox
		sudo apt update
		sudo apt install fasttrack-archive-keyring
		echo "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib" | sudo tee -a /etc/apt/sources.list
		echo "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib" | sudo tee -a /etc/apt/sources.list
		sudo apt update
		sudo apt install virtualbox virtualbox-ext-pack
	}
}

function install_debian_pkgs() {
	sudo apt update
	sudo apt-get -y install \
		wget curl \
		tmux neovim
	sudo apt-get -y install \
		gcc g++ gdb \
		clang \
		cmake ninja-build \
		gtest
	sudo apt-get -y install \
		python3 python3-pip
	sudo apt-get -y install \
		shellcheck
}

function install_packages() {
	packages=(
	# Base
		wget
		curl
		neovim
		tmux
	# C/C++
		cmake
		ninja
		gcc
		gtest
		clang
	# Python
		python
		python-pip
	# Shell
		shellcheck
	)

	if command -v pacman >/dev/null; then
		sudo pacman -Sy --needed --noconfirm "${packages[@]}"
	elif command -v apt >/dev/null; then
		install_debian_pkgs
	else
		echo "Error: unknown package manager. Skipping installing system packages"
	fi
}

function install_pip() {
	modules=(
		neovim
	)

	pip install "${modules[@]}"
}

function install_zsh_plugins() {
	local PLUGINS_DIR="${HOME}/.config/zsh/plugins"
	mkdir -p "$PLUGINS_DIR"

	# zsh-autosuggestions
	rm -rf "${PLUGINS_DIR}/zsh-autosuggestions{,-0.7.0}"
	curl -fsSL "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz" \
		| tar -xz -C "${PLUGINS_DIR}"
	ln -sf "${PLUGINS_DIR}/zsh-autosuggestions-0.7.0" "${PLUGINS_DIR}/zsh-autosuggestions"

	# zsh-completions
	rm -rf "${PLUGINS_DIR}/zsh-completions{,0.33.0}"
	curl -fsSL "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.33.0.tar.gz" \
		| tar -xz -C "${PLUGINS_DIR}"
	ln -sf "${PLUGINS_DIR}/zsh-completions-0.33.0" "${PLUGINS_DIR}/zsh-completions"

	# zsh-syntax-highlighting
	rm -rf "${PLUGINS_DIR}/zsh-syntax-highlighting{,-0.7.1}"
	curl -fsSL "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.7.1.tar.gz" \
		| tar -xz -C "${PLUGINS_DIR}"
	ln -sf "${PLUGINS_DIR}/zsh-syntax-highlighting-0.7.1" "${PLUGINS_DIR}/zsh-syntax-highlighting"

	# zsh-history-substring-search
	rm -rf "${PLUGINS_DIR}/zsh-history-substring-search{,-1.0.2}"
	curl -fsSL "https://github.com/zsh-users/zsh-history-substring-search/archive/refs/tags/v1.0.2.tar.gz" \
		| tar -xz -C "${PLUGINS_DIR}"
	ln -sf "${PLUGINS_DIR}/zsh-history-substring-search-1.0.2" "${PLUGINS_DIR}/zsh-history-substring-search"
}

install_virtual_box
install_packages
install_pip
install_zsh_plugins
