#!/bin/sh

# Color support for ls
if uname -s | grep -Eq "Darwin"; then
    alias ls='ls -G'
elif uname -s | grep -Eq "Linux|MINGW|CYGWIN"; then
    alias ls="ls --color=auto"
fi

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -v'
alias ll='ls -lhFA'
alias la='ls -CFA'
alias l='ls -CF'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

alias :q="exit"

alias vim="nvim"

alias ezc='$EDITOR $ZDOTDIR/.zshrc'
alias szc='. $ZDOTDIR/.zshrc'
alias evc='$EDITOR $MYVIMRC'
alias etc='$EDITOR $XDG_CONFIG_HOME/tmux/tmux.conf'
alias eac='$EDITOR $XDG_CONFIG_HOME/shell/aliases'

# Mount NTFS external drive (MacOS)
# Usage: sudo umount /dev/disk2s1 && mnt-ntfs /dev/disk2s1 /Volumes/NTFS
alias mnt-ntfs='sudo ntfs-3g -o local -o allow-other -o auto_xattr'

# GIT
alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gl="git log"
alias gds='git diff --staged'
alias gcm='git commit'
alias gco='git checkout'

# Kitty
# https://sw.kovidgoyal.net/kitty/faq/?highlight=ssh#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer
command -v kitty >/dev/null && alias ssh="kitty +kitten ssh"

# Source local aliases
[ -f "$XDG_CONFIG_HOME/shell/aliases.local" ] && . "$XDG_CONFIG_HOME/shell/aliases.local"
