#!/bin/sh

# System
export PATH=$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH
export EDITOR='nvim'
export LC_ALL="en_US.UTF-8"

# Add LLVM to path
LLVM_BIN_DIR="/usr/local/opt/llvm/bin"
[ -d "$LLVM_BIN_DIR" ] && export PATH="${LLVM_BIN_DIR}:${PATH}"

# Rust
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Nodejs
[ -d "${HOME}/.local/opt/nodejs/bin" ] && export PATH="${HOME}/.local/opt/nodejs/bin:${PATH}"

# Colored GCC warnings and errors
export GTEST_COLOR=1
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Source local exports
[ -f "$XDG_CONFIG_HOME/shell/exports.local" ] && . "$XDG_CONFIG_HOME/shell/exports.local"
